# Generated by Django 4.2.2 on 2023-06-26 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_rename_user_movie_added_by_alter_movie_duration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
    ]
