# Generated by Django 4.2.2 on 2023-06-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_rename_added_by_movie_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="user",
            new_name="added_by",
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
