# Generated by Django 4.2.2 on 2023-06-26 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_user_movie_added_by_alter_movieorder_buyed_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
    ]
