# Generated by Django 4.2.2 on 2023-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movieorder_buyed_at_alter_movieorder_buyed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
